config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#homepage'
  get 'services', to: 'static_pages#all_services'
  resources "contacts", only: [:new, :create]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:index, :show]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :content
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  validates :email, presence: true, uniqueness: true,	format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:success] = "Votre demande à bien été prise en compte"
      redirect_to root_path
    else
      flash.now[:notice] = "Votre demande n'a pas été prise en compte"
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  # def new
	#    @post = Post.new
  # end

  # def create
	# 	@post = Post.new(post_params)
	#   if @post.save
	#     redirect_to post_path(@post.id), notice: "Article créé avec succès"
	#   else
  #
	#   end
  # end
  #
  # def edit
  # end
  #
  # def update
  #
  # end
  #
  # def destroy
  #
  # end

  private

    def post_params
      params.require(:post).permit(:title, :content)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def homepage
  end

  def all_services
  end

  def uikit
  end

  def navbar
  end

  def form
  end

  def footer
  end

  def form_sign_in
  end

  def cart
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/contacts/new.html.erb
<div class="jumbotron jumbotron-fluid text-light pt-5 space-3 space-lg-3">
  <div class="container text-center">
    <h1 class="display-4 text-light">Nous contacter</h1>
    <!-- <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p> -->
  </div>
</div>


<main>
  <!-- Contact Form Section -->
  <div class="container space-top-1 space-top-lg-2 space-bottom-2">
    <div class="row">
      <div class="col-lg-6 mb-9 mb-lg-0">
        <div class="mb-5">
          <h3 class="text-primary">Agence Web Marketing à Paris et Aix-en Provence</h3><br>
          <h1>Augmentez votre Chiffre d’Affaires Vitesse Grand V grâce au Web</h1><br>
          <p>Nous aidons les PME avec de petites équipes marketing à accélérer la génération de leads ou de ventes grâce au webmarketing.</p>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="ml-lg-5">
          <!-- Form -->
          <div class="js-validate card shadow-lg mb-4">
            <div class="card-header border-0 bg-blue text-center py-4 px-4 px-md-6">
              <h2 class="h4 mb-0">Discutons de votre projet 🚀</h2>
            </div>

            <div class="card-body p-4 p-md-6">
              <div class="row">
                <div class="col-sm-12">
                  <%= simple_form_for @contact do |f| %>
                    <%= f.input :name, placeholder:"Nataly"%>
                    <%= f.input :email, placeholder:"nayagaga@pixeel.com" %>
                    <%= f.input :message, placeholder:"Hi there, I would like to ..." %>
                    <%= f.button :submit, "Nous contacter", class: " btn-block btn-primary" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <!-- End Form -->

          <div class="text-center">
            <p class="small">Nous analysons votre site, votre secteur d’activité et vous recontactons dans les 24h.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Contact Form Section -->
</main>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-light text-black">
  <div class="container">
    <div class="space-top-2 space-bottom-1 space-bottom-lg-2">
      <div class="row justify-content-lg-between">
        <div class="col-lg-3 ml-lg-auto mb-5 mb-lg-0">
          <!-- Logo -->
          <div class="mb-4">

          </div>
          <!-- End Logo -->

          <!-- Nav Link -->
          <ul class="nav nav-sm nav-x-0 nav-black flex-column">
            <li class="nav-item">
              <a class="nav-link media" href="javascript:;">
                <span class="media">
                  <span class="fas fa-location-arrow mt-1 mr-2"></span>
                  <span class="media-body">
                    Paris et Aix-en-Provence
                  </span>
                </span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link media" href="tel:1-062-109-9222">
                <span class="media">
                  <span class="fas fa-phone-alt mt-1 mr-2"></span>
                  <span class="media-body">
                    agence@owanted.io
                  </span>
                </span>
              </a>
            </li>
          </ul>
          <!-- End Nav Link -->
        </div>

        <div class="col-6 col-md-3 col-lg mb-5 mb-lg-0">
          <h5 class="text-black">L'agence</h5>

          <!-- Nav Link -->
          <ul class="nav nav-sm nav-x-0 nav-black flex-column">
            <li class="nav-item"><a class="nav-link" href="#">Accueil</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Cas clients <span class="badge badge-primary ml-1">We're hiring</span></a></li>
            <li class="nav-item"><a class="nav-link" href="#">A propos</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Nous contacter</a></li>
          </ul>
          <!-- End Nav Link -->
        </div>

        <div class="col-6 col-md-3 col-lg mb-5 mb-lg-0">
          <h5 class="text-black">Nos services</h5>

          <!-- Nav Link -->
          <ul class="nav nav-sm nav-x-0 nav-black flex-column">
            <li class="nav-item"><a class="nav-link" href="#">Campagnes SEA</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Publicité sur les Réseaux Sociaux</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Optimisation UX et CRO</a></li>
            <li class="nav-item"><a class="nav-link" href="#">Référencement SEO</a></li>
          </ul>
          <!-- End Nav Link -->
        </div>

        <div class="col-6 col-md-3 col-lg">
          <h5 class="text-black">Nous contacter</h5>

          <!-- Nav Link -->
          <ul class="nav nav-sm nav-x-0 nav-black flex-column">
            <li class="nav-item"><a class="nav-link" href="#">Paris et Aix-en-Provence</a></li>
            <li class="nav-item"><a class="nav-link" href="#">agence@owanted.io</a></li>
          </ul>
          <!-- End Nav Link -->
        </div>
      </div>
    </div>

    <hr class="opacity-xs my-0 color-black">

    <div class="space-1">
      <div class="row align-items-md-center mb-7">
        <div class="col-md-6 mb-4 mb-md-0">
          <!-- Nav Link -->
          <ul class="nav nav-sm nav-black nav-x-sm align-items-center">
            <li class="nav-item">
              <a class="nav-link" href="#">Privacy &amp; Policy</a>
            </li>
            <li class="nav-item opacity mx-3">&#47;</li>
            <li class="nav-item">
              <a class="nav-link" href="#">Terms</a>
            </li>
            <li class="nav-item opacity mx-3">&#47;</li>
            <li class="nav-item">
              <a class="nav-link" href="#">Site Map</a>
            </li>
          </ul>
          <!-- End Nav Link -->
        </div>

        <div class="col-md-6 text-md-right">
          <ul class="list-inline mb-0">
            <!-- Social Networks -->
            <li class="list-inline-item">
              <a class="btn btn-xs btn-icon btn-secondary" href="#">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn btn-xs btn-icon btn-secondary" href="#">
                <i class="fab fa-google"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn btn-xs btn-icon btn-secondary" href="#">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a class="btn btn-xs btn-icon btn-secondary" href="#">
                <i class="fab fa-github"></i>
              </a>
            </li>
            <!-- End Social Networks -->
          </ul>
        </div>
      </div>

      <!-- Copyright -->
      <div class="w-md-75 text-lg-center mx-lg-auto">
        <p class="text-black opacity-md small">&copy; Owanted 2020. Tous droits réservés.</p>
        <p class="text-black opacity-md small">When you visit or interact with our sites, services or tools, we or our authorised service providers may use cookies for storing information to help provide you with a better, faster and safer experience and for marketing purposes.</p>
      </div>
      <!-- End Copyright -->
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary sticky-top">
      <a class="navbar-brand" href="#">Owanted</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Accueil", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Services", services_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Blog", posts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Nous contacter", new_contact_path, class: "nav-link" %>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Profil", user_path(current_user), class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "nav-link"  %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Connexion", new_user_session_path, class: "nav-link"  %></li>
            <li class="nav-item"><%= link_to "Inscription", new_user_registration_path, class: "nav-link"  %></li>
          <% end %>
        </ul>
      </div>
    </nav>

app/views/layouts/_work_together.html.erb
<!-- CTA Section -->
<div class="bg-gradient text-center bg-img-hero">
  <div class="container space-2">
    <div class="mb-5">
      <p class="h1 text-white">Démarrons un projet ensemble</p>
    </div>
    <a class="btn btn-primary transition-3d-hover" href="#">Nous contacter</a>
  </div>
</div>
<!-- End CTA Section -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Owanted</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&family=Roboto:wght@100;300;400;500;700&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application'%>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash" %>
    <%= yield %>
    <%= render "layouts/footer" %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>

    <div class="field">
        <%= f.label :content %>
        <%= f.rich_text_area :content %>
    </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Back', posts_path %>

app/views/static_pages/_services_section.html.erb
<div class="row justify-content-lg-between align-items-lg-center">
  <div class="col-lg-6 mb-9 mb-lg-0">
    <div class="mb-3">
      <h3 class="h1">Campagnes SEA</h3>
      <p class="text-primary font-weight-bold">Investir correctement dans la publicité en Ligne</p>
    </div>
    <p>En 2020, 75% du budget investi sur Google et Facebook Ads est perdu à cause de campagnes mal optimisées. Nous nous imprégnons de votre secteur d’activité, de vos problématiques et de votre marché pour dessiner une stratégie efficace et rentable.</p>
    <div class="mt-4">
      <a class="btn btn-primary btn-wide transition-3d-hover" href="#">Start Now</a>
    </div>
  </div>

  <div class="col-lg-6 col-xl-5">
  </div>
</div>
<div class="row justify-content-lg-between align-items-lg-center">
  <div class="col-lg-6 col-xl-5">
  </div>

  <div class="col-lg-6 mb-9 mb-lg-0">
    <div class="mb-3">
      <h3 class="h1">Publicité sur les Réseaux Sociaux</h3>
      <p class="text-primary font-weight-bold">Votre message publicitaire au bon endroit au bon moment</p>
    </div>
    <p>Les réseaux sociaux savent tout de chacun de leurs utilisateurs. Un mal pour un bien. Ils offrent la possibilité de cibler des millions de consommateurs et à entrer en contact avec eux grâce aux audiences et à des tests publicitaires ultra-spécifiques.</p>
    <div class="mt-4">
      <a class="btn btn-primary btn-wide transition-3d-hover" href="#">Start Now</a>
    </div>
  </div>
</div>
<div class="row justify-content-lg-between align-items-lg-center">
  <div class="col-lg-6 mb-9 mb-lg-0">
    <div class="mb-3">
      <h3 class="h1">CRO & UX Design</h3>
      <p class="text-primary font-weight-bold">Optimiser votre site pour devenir rentable</p>
    </div>
    <p>Recevoir du trafic sur un site qui n’est pas optimisé pour convertir est le meilleur moyen pour rater de nombreuses opportunités. Nous analysons votre site web en profondeur pour vous faire remonter les incohérences qui gâchent l’expérience utilisateur et … empêchent les visiteurs de passer à l’action.</p>
    <div class="mt-4">
      <a class="btn btn-primary btn-wide transition-3d-hover" href="#">Start Now</a>
    </div>
  </div>

  <div class="col-lg-6 col-xl-5">
  </div>
</div>
<div class="row justify-content-lg-between align-items-lg-center">
  <div class="col-lg-6 col-xl-5">
  </div>

  <div class="col-lg-6 mb-9 mb-lg-0">
    <div class="mb-3">
      <h3 class="h1">Référencement Naturel SEO</h3>
      <p class="text-primary font-weight-bold">Atteindre la première position sur Google</p>
    </div>
    <p>Rien ne sert d’avoir le plus beau site de votre secteur si personne ne peut le voir ! Nous vous aidons à ressortir dans les premières positions des moteurs de recherches sur les principaux mots clés de votre activité.</p>
    <div class="mt-4">
      <a class="btn btn-primary btn-wide transition-3d-hover" href="#">Start Now</a>
    </div>
  </div>
</div>

app/views/static_pages/all_services.html.erb
<div class="jumbotron jumbotron-fluid text-light pt-5 space-3 space-lg-3">
  <div class="container text-center">
    <h1 class="display-4 text-light">Nos Prestations</h1>
    <!-- <p class="lead">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p> -->
  </div>
</div>


<main id="content" role="main">
  <div id="featuresSection" class="container space-2 space-lg-2">
    <%= render "static_pages/services_section" %>
  </div>
  </main>
  <%= render "layouts/work_together" %>
</main>

app/views/static_pages/homepage.html.erb
<main id="content" role="main">

<div class="position-relative bg-gradient overflow-hidden">
  <div class="container position-relative z-index-2 space-top-3 space-top-md-3 space-bottom-3 space-bottom-md-3">
    <div class="w-md-90 w-xl-90 text-center mx-md-auto">
      <div class="mb-7">
        <p class="lead text-primary mb-5">Agence Web Marketing à Aix-en-Provence et Paris</p>
        <h1 class="display-4 text-white mb-4">Augmentez votre Chiffre d’Affaires Vitesse Grand V grâce au Web</h1>
        <p class="lead text-white mb-4">Nous aidons les PME avec de petites équipes marketing à accélérer  la génération de leads ou de ventes grâce au webmarketing</p>
      </div>
      <a class="btn btn-primary btn-wide transition-3d-hover" href="#">Nous contacter</a>
    </div>
  </div>
</div>
  <!-- Clients Section -->
  <div class="border-bottom">
    <div class="container space-1 space-top-md-0">
      <div class="w-lg-80 mx-lg-auto">
        <div class="row justify-content-center">
          <div class="col-4 col-sm-3 col-md my-2">
            <img class="max-w-11rem max-w-md-13rem mx-auto" src="../../assets/svg/clients-logo/airbnb.svg" alt="Image Description">
          </div>
          <div class="col-4 col-sm-3 col-md my-2">
            <img class="max-w-11rem max-w-md-13rem mx-auto" src="../../assets/svg/clients-logo/slack.svg" alt="Image Description">
          </div>
          <div class="col-4 col-sm-3 col-md my-2">
            <img class="max-w-11rem max-w-md-13rem mx-auto" src="../../assets/svg/clients-logo/fitbit.svg" alt="Image Description">
          </div>
          <div class="col-4 col-sm-3 col-md my-2">
            <img class="max-w-11rem max-w-md-13rem mx-auto" src="../../assets/svg/clients-logo/hubspot.svg" alt="Image Description">
          </div>
          <div class="col-4 col-sm-3 col-md my-2">
            <img class="max-w-11rem max-w-md-13rem mx-auto" src="../../assets/svg/clients-logo/weebly.svg" alt="Image Description">
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- End Clients Section -->


  <!-- Articles Section -->
  <div class="container space-2">
    <!-- Title -->
    <div class="w-md-80 w-lg-80 text-center mx-md-auto mb-5 mb-md-9">
      <h2 class="h1">Renforcez votre équipe marketing</h2>
    </div>
    <!-- End Title -->

    <div class="row">
      <div class="col-md-6 col-lg-4 mb-4 mb-md-5 mb-lg-0">
        <!-- Card -->
        <div class="card shadow-soft h-100 text-center transition-3d-hover">
          <div class="card-body pt-7 px-7">
            <figure class="avatar mx-auto mb-4">
              <img class="avatar-img" src="../../assets/img/160x160/img20.png" alt="Logo">
            </figure>
            <h3>Une stratégie web claire</h3>
            <p class="text-body">Nous challengeons votre stratégie et vous la partageons de manière claire et transparente. Pas d’enfumage à grands coups de termes techniques, c’est promis.</p>
          </div>
        </div>
        <!-- End Card -->
      </div>

      <div class="col-md-6 col-lg-4 mb-4 mb-md-5 mb-lg-0">
        <!-- Card -->
        <div class="card shadow-soft h-100 text-center transition-3d-hover">
          <div class="card-body pt-7 px-7">
            <figure class="avatar mx-auto mb-4">
              <img class="avatar-img" src="../../assets/img/160x160/img35.png" alt="Logo">
            </figure>
            <h3>Des leads qualifiés</h3>
            <p class="text-body">Nous ne nous contentons pas de capter du trafic. Plus que de simples visiteurs, nous attirons des “prospects chauds” qui seront plus facile à convertir en clients. </p>
          </div>
        </div>
        <!-- End Card -->
      </div>

      <div class="col-md-6 col-lg-4">
        <!-- Card -->
        <div class="card shadow-soft h-100 text-center transition-3d-hover">
          <div class="card-body pt-7 px-7">
            <figure class="avatar mx-auto mb-4">
              <img class="avatar-img" src="../../assets/img/160x160/img36.png" alt="Logo">
            </figure>
            <h3>Des campagnes rentables</h3>
            <p class="text-body">Nous restons concentré sur un chiffre clé : le retour sur investissement. Chaque euro investi doit contribuer à diminuer votre coût d’acquisition.</p>
          </div>
        </div>
        <!-- End Card -->
      </div>
    </div>
  </div>
  <!-- End Articles Section -->


  <div id="featuresSection" class="container space-2 space-lg-2">
    <div class="overflow-hidden">
      <div class="container pb-4">
        <!-- Title -->
        <div class="w-md-80 w-lg-80 text-center mx-md-auto mb-9">
          <h2 class="h1">Ce qu’on peut faire pour vous aider</h2>
        </div>
      </div>
    </div>
    <%= render "static_pages/services_section" %>
  </div>
</main>
<%= render "layouts/work_together" %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>